### PR TITLE
notion: add basic flow of notion to Anki syncer

### PR DESCRIPTION
**Pull request by balta2ar**

### CODE REVIEW

**Comment by dummifiedme** [comment]
Is if possible to have a notion to anki sync? I was using Notion2Anki, but it's tedious to have to upload every now and then. Can you suggest your workflow here?

**Comment by balta2ar** [comment]
@dummifiedme I have a cronjob that does the sync for me. At least, it should. I haven't really tested it much just yet, still super alpha.

```
0 5 * * * timeout 600 xvfb-run -a -e /var/log/xvfb-run.log $HOME/.local/bin/srst-anki-sync-notion --block-id '<block-id-of-some-root-notion-page>' --anki-media '/home/user/.local/share/Anki2/username/collection.media' --anki-sync
```

`yatetradki/tools/anki_notion.py` is the script that does the sync.

**Comment by dummifiedme** [comment]
As far as I could understand, its like a scheduler to run that particular python script, but how do you convert the notes to anki cards? What format do you follow? Or you go via Notion2Anki?

**Comment by balta2ar** [comment]
> Or you go via Notion2Anki?

That's correct. I suggest rewriting conversion code into Python (https://github.com/alemayhu/notion2anki/issues/205#issuecomment-717441006), but it's unlikely to happen.

**Comment by dummifiedme** [comment]
I am not that proficient in programming, just a few tweaks here and there if I dig my head in. I am essentially a mechanical engineer.

I did try to look into the code, and interacted with someone who made changes to the code for his case (Cornell notes), requested him to help out. 
He too was skeptical about lmda used here. And, told me it's better not to alter the code, as its too complex

**Comment by dummifiedme** [comment]
So, this python script of yours automatically downloads zip, uploads on 2anki.net and gets apkg?
Or the 2anki part manual?

**Comment by balta2ar** [comment]
It does the following:
1. Downloads zip file from Notion
2. Uploads it to 2anki to obtain apkg
3. Imports that apkg into locally-installed anki instance
4. Runs anki sync so that I can sync mobile app later and review the notes

**Comment by dummifiedme** [comment]
Damn, this is what I needed. Thanks a lot!
I will give it a try.

**Comment by dummifiedme** [comment]
Is there somewhere I can message you?
Reddit or something?
If you can help me set it up, it would be really a great help.

**Pull request merged**
